"""Importing a real open-source design: SO-101 from vendored STEP + URDF.

These are the tests that would have caught what the import actually got wrong
the first time — a bench arm judged as though it were free-standing, and four
joints reported as detached because the criterion was looking at a third of
each body.
"""

import json
import math
from pathlib import Path

import pytest

from engine.evaluate import compute_mass_properties, evaluate
from engine.ir import RobotIR

_IR = Path(__file__).parents[2] / "designs" / "so101_arm.ir.json"
_VENDOR = Path(__file__).parents[2] / "vendor" / "so101"


def _so101() -> RobotIR:
    if not _IR.exists():  # pragma: no cover - generated by designs/so101_arm.py
        pytest.skip("so101_arm.ir.json not generated")
    return RobotIR.model_validate(json.loads(_IR.read_text(encoding="utf-8")))


def _needs_vendor():
    if not (_VENDOR / "step").is_dir():  # pragma: no cover
        pytest.skip("SO-101 assets not vendored")


def test_every_link_builds_from_a_real_solid():
    _needs_vendor()
    ir = _so101()
    props = compute_mass_properties(ir)
    assert set(props) == {link.id for link in ir.links}
    assert all(mp.mass > 0 and mp.volume > 0 for mp in props.values())


def test_the_massless_tool_frame_is_not_imported_as_a_body():
    """SO-101's `gripper_frame_link` is a tool centre point carrying 1e-9 kg and
    a zero inertia tensor. Importing it as a body would fail `inertia_valid` for
    being non-positive-definite — true, and useless."""
    assert not any(link.id.startswith("gripper_frame") for link in _so101().links)


def test_servos_are_massed_from_the_datasheet_not_from_density():
    """A servo is steel, copper, magnet and plastic in a case. Density times
    bounding volume is not its mass, and no single material makes it so."""
    _needs_vendor()
    ir = _so101()
    props = compute_mass_properties(ir)
    servos = [lid for lid in props if lid.endswith("__servo")] + [
        link.id for link in ir.links if link.geometry.generator == "component"
    ]
    assert servos, "the import produced no servo components"
    for link_id in set(servos):
        assert props[link_id].mass == pytest.approx(0.055, rel=1e-6)


def test_step_parts_are_pinned_by_content_hash():
    """Without the hash the IR names a file rather than a robot, and re-running
    against an updated vendor drop would silently evaluate a different design."""
    for link in _so101().links:
        if link.geometry.generator == "step_part":
            assert len(str(link.geometry.params["sha256"])) == 64


def test_a_tampered_asset_is_refused():
    _needs_vendor()
    from engine.assets import load_step

    with pytest.raises(ValueError, match="does not match the sha256"):
        load_step("so101/step/Upper_arm_SO101.step", sha256="0" * 64)


def test_an_asset_path_cannot_escape_the_asset_root():
    """An IR is agent-authored, and `../../etc/passwd` is a path an agent can write."""
    from engine.assets import resolve_asset

    with pytest.raises(ValueError, match="escapes the asset root"):
        resolve_asset("../../../../etc/passwd")


def test_fixed_base_means_no_static_margin():
    """A bolted-down arm cannot tip. Free-standing, SO-101's centre of mass sits
    1.56 support half-widths past its own footprint whenever it reaches for
    anything, so the criterion would fail every arm that can reach."""
    _needs_vendor()
    ir = _so101()
    assert ir.base == "fixed"
    assert not any(r.name == "static_margin" for r in evaluate(ir, max_tier=0).results)

    floating = ir.model_copy(deep=True)
    floating.base = "floating"
    margin = [r for r in evaluate(floating, max_tier=0).results if r.name == "static_margin"]
    assert margin and not margin[0].passed, "free-standing, this arm should topple"


def test_fixed_base_is_not_given_a_free_joint():
    _needs_vendor()
    from engine.sim.mujoco_harness import compile_floating, has_free_base

    model = compile_floating(_so101())
    assert not has_free_base(model)
    # Six revolute joints, and nothing else — no 6-dof base.
    assert model.nv == 6


def test_sim_loads_accounts_for_the_welded_base():
    """MuJoCo welds a URDF root to the world and a welded body carries no mass.
    For a fixed base that is correct, so the expected total has to exclude it —
    comparing against the full authored mass would report a shortfall on every
    bench arm forever."""
    _needs_vendor()
    result = {r.name: r for r in evaluate(_so101(), max_tier=2).results}["sim_loads"]
    assert result.passed
    assert "welded base" in result.detail


def test_the_arm_settles_without_falling_over():
    _needs_vendor()
    result = {r.name: r for r in evaluate(_so101(), max_tier=2).results}["settles"]
    assert result.passed, result.detail


def test_rigid_groups_gather_parts_welded_into_one_body():
    """One physical body is several IR links here: a printed bracket plus a servo
    plus a motor holder, all bolted solid."""
    _needs_vendor()
    from engine.criteria.assembly_checks import rigid_groups

    groups = rigid_groups(_so101())
    base = groups["base_link"]
    assert len(base) == 4, base  # base + motor holder + servo + mounting plate
    assert all(groups[member] == base for member in base)


def test_link_attached_measures_whole_bodies_not_frame_carriers():
    """Measuring frame-carrier against frame-carrier reported four SO-101 joints
    as detached by up to 73 mm. The arm was fine; the criterion was looking at a
    third of it."""
    _needs_vendor()
    attached = [r for r in evaluate(_so101(), max_tier=0).results if r.name.startswith("link_attached")]
    assert attached
    assert all(r.passed for r in attached), [r.detail for r in attached if not r.passed]


def test_backlash_refuses_to_read_a_missing_datasheet_figure_as_zero():
    """The STS3215 is a 345:1 geared servo whose play nobody has transcribed.
    Reporting that as zero would turn a catalogue gap into a passing criterion."""
    _needs_vendor()
    result = {r.name: r for r in evaluate(_so101(), max_tier=1).results}["backlash"]
    assert not result.passed
    assert "cannot be measured" in result.detail
    assert "345:1" in result.detail


def test_the_import_is_the_published_topology():
    """Joint names, kinds and limits come from the vendored URDF, so the IR
    cannot drift from the published design without the vendored file changing."""
    _needs_vendor()
    ir = _so101()
    revolute = {j.id for j in ir.joints if j.kind == "revolute"}
    assert revolute == {
        "shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll", "gripper",
    }
    shoulder = next(j for j in ir.joints if j.id == "shoulder_pan")
    assert shoulder.limits.lower.value == pytest.approx(-1.91986)
    assert shoulder.limits.upper.value == pytest.approx(1.91986)
    assert shoulder.limits.lower.provenance.status == "MEASURED"


def test_joint_torque_stays_within_the_servo_rating():
    """The STS3215 stalls at 30 kgf*cm = 2.942 N*m. An unloaded SO-101 holding
    itself out should need a fraction of that; needing most of it would mean the
    mass model is wrong."""
    _needs_vendor()
    budgets = [
        r for r in evaluate(_so101(), max_tier=1).results
        if r.name.startswith("joint_torque_budget")
    ]
    assert len(budgets) == 6
    assert all(r.passed for r in budgets), [r.detail for r in budgets if not r.passed]
