"""`payload` and `backlash` — the two criteria that drove the prototype's loop.

The interesting cases are the ones about what the criteria refuse to answer: a
rover with no arm gets no result rather than a failure, and a pose sweep that
never puts the load outside the footprint says so instead of reporting a number
it did not measure.
"""

import json
import math
from pathlib import Path

import pytest

from engine.evaluate import compute_mass_properties, evaluate
from engine.ir import CatalogueParam, RobotIR

_DESIGNS = Path(__file__).parents[2] / "designs"
_ARM = _DESIGNS / "rover_arm_3axis.ir.json"
_ROVER = _DESIGNS / "rover_4wd_300mm.ir.json"

_GEARED = CatalogueParam(value="nema17_planetary_13.73", catalogue="stepper_motors")
_ARM_JOINTS = ("yaw", "shoulder", "elbow", "wrist")


def _load(path: Path) -> RobotIR:
    if not path.exists():  # pragma: no cover - generated by the designs/ scripts
        pytest.skip(f"{path.name} not generated")
    return RobotIR.model_validate(json.loads(path.read_text(encoding="utf-8")))


def _results(ir: RobotIR, max_tier: int = 1) -> dict:
    return {r.name: r for r in evaluate(ir, max_tier=max_tier).results}


def test_the_armless_rover_gets_no_reach_criteria_at_all():
    """A rover with no arm is not a rover with a bad arm. Emitting a failure
    would make every armless base unbuildable — the criterion-nobody-can-pass
    trap — and `EvaluationReport.passed` already refuses to call a report with
    no results a pass."""
    names = _results(_load(_ROVER))
    assert "payload" not in names
    assert "backlash" not in names


def test_the_arm_design_reports_a_measured_payload():
    payload = _results(_load(_ARM))["payload"]
    assert payload.passed
    assert payload.magnitude > 1.0  # ratio against the 500 g target
    assert "worst pose" in payload.detail


def test_payload_is_the_worst_pose_not_the_home_pose():
    """The sweep is the whole point. Reaching straight forward is over the long
    axis of the footprint; reaching sideways is over the short one, and that is
    where the robot actually tips. A criterion evaluated only at home would
    report the easy number."""
    from engine.criteria.tier1_reach import _arm_reach

    ir = _load(_ARM)
    props = compute_mass_properties(ir)
    swept = {r.name: r for r in _arm_reach(ir, props)}["payload"]

    # Pin the arm to the home pose by collapsing every arm joint's travel to zero.
    home_only = ir.model_copy(deep=True)
    for joint in home_only.joints:
        if joint.id in _ARM_JOINTS:
            joint.limits.lower = joint.limits.lower.model_copy(update={"value": 0.0})
            joint.limits.upper = joint.limits.upper.model_copy(update={"value": 0.0})
    pinned = {r.name: r for r in _arm_reach(home_only, compute_mass_properties(home_only))}["payload"]

    assert swept.magnitude < pinned.magnitude, (
        "sweeping the arm must find a pose at least as bad as home; "
        f"got swept={swept.magnitude:.3f} vs home={pinned.magnitude:.3f}"
    )


def test_a_direct_drive_arm_has_no_backlash():
    backlash = _results(_load(_ARM))["backlash"]
    assert backlash.passed
    assert backlash.magnitude == pytest.approx(0.0)
    assert "direct drive" in backlash.detail


def test_gearing_the_shoulder_buys_torque_and_pays_in_backlash():
    """The coupling the prototype documented, asserted rather than remembered:
    "a gearbox fixes arm_holds cheaply but introduces backlash, which is why
    that criterion exists at all."

    This is also why `rover_arm_3axis` is direct-drive. The reason stays
    checkable here instead of becoming folklore in a docstring.
    """
    ir = _load(_ARM)
    direct = _results(ir)

    geared_ir = ir.model_copy(deep=True)
    for joint in geared_ir.joints:
        if joint.id == "shoulder":
            joint.actuator = _GEARED
    geared = _results(geared_ir)

    # Bought: 13.73:1 through 81% efficiency, so the shoulder margin improves.
    assert (
        geared["joint_torque_budget[shoulder]"].magnitude
        > direct["joint_torque_budget[shoulder]"].magnitude
    )
    # Paid for: 60 arcmin at a ~305 mm lever is ~5 mm against a 2 mm budget.
    assert direct["backlash"].passed
    assert not geared["backlash"].passed
    assert geared["backlash"].magnitude > 2.0


def test_backlash_lever_is_perpendicular_distance_to_the_axis():
    """Play about an axis pointing straight at the end effector moves it not at
    all, so the lever is the perpendicular distance, never the straight-line one.

    Yaw's axis is vertical, so its lever is the *horizontal* reach. The pose that
    puts the tip furthest from the base is the arm stretched straight up, where
    that horizontal distance is nearly zero — which is why the criterion searches
    for the pose that maximises slop rather than the one that maximises reach.
    """
    from engine.criteria.tier1_reach import _arm_reach

    ir = _load(_ARM)
    yaw_only = ir.model_copy(deep=True)
    for joint in yaw_only.joints:
        if joint.id == "yaw":
            joint.actuator = _GEARED

    backlash = {r.name: r for r in _arm_reach(yaw_only, compute_mass_properties(yaw_only))}["backlash"]
    play = math.radians(1.0)  # 60 arcmin
    slop = backlash.magnitude * 0.002
    # Horizontal reach at full extension is ~0.305 m from the yaw axis at x=0.
    assert slop == pytest.approx(play * 0.305, rel=0.2), backlash.detail


def test_an_unmeasurable_payload_is_reported_not_invented():
    """An arm that never leaves the footprint gives the criterion nothing to
    weigh. Reporting a pass there would be the silence-as-consent failure."""
    from engine.criteria.tier1_reach import _arm_reach

    ir = _load(_ARM)
    stubby = ir.model_copy(deep=True)
    # Shrink every arm segment so the gripper stays well inside the wheelbase.
    for link in stubby.links:
        if link.id in ("link_shoulder", "link_elbow", "gripper"):
            link.geometry.params["length"] = link.geometry.params["length"].model_copy(
                update={"value": 0.005}
            )
    for joint in stubby.joints:
        if joint.id in ("elbow", "wrist"):
            joint.origin.position.x = 0.005

    payload = {r.name: r for r in _arm_reach(stubby, compute_mass_properties(stubby))}["payload"]
    assert not payload.passed
    assert "no sampled pose" in payload.detail


def test_reach_criteria_are_tier_1_and_run_before_contact_simulation():
    report = evaluate(_load(_ARM), max_tier=1)
    assert report.tiers_run == [0, 1]
    assert {"payload", "backlash"} <= {r.name for r in report.results}


def test_the_arm_design_passes_every_tier_through_contact_simulation():
    report = evaluate(_load(_ARM), max_tier=2)
    assert report.tiers_run == [0, 1, 2]
    assert report.passed, [f"{r.name}: {r.detail}" for r in report.failures]
