"""Tier 2: MuJoCo contact simulation.

The tests that matter here are the ones about the harness lying convincingly —
a welded root simulates cleanly, settles perfectly, and is not the robot that
was authored.
"""

import json
import math
from pathlib import Path

import mujoco
import pytest

from engine.evaluate import compute_mass_properties, evaluate
from engine.examples import simple_rover
from engine.export.urdf import to_urdf
from engine.ir import RobotIR
from engine.sim.mujoco_harness import compile_floating, drive, settle, total_mass

_ROVER = Path(__file__).parents[2] / "designs" / "rover_4wd_300mm.ir.json"


def _rover() -> RobotIR:
    if not _ROVER.exists():  # pragma: no cover - generated by designs/rover_4wd_300mm.py
        pytest.skip(f"{_ROVER.name} not generated")
    return RobotIR.model_validate(json.loads(_ROVER.read_text(encoding="utf-8")))


def _authored_mass(ir: RobotIR) -> float:
    return sum(mp.mass for mp in compute_mass_properties(ir).values())


def test_a_urdf_root_is_welded_and_silently_loses_its_mass():
    """The trap, demonstrated rather than described.

    MuJoCo has no notion of a floating base in URDF, so it welds the root body
    to the world and drops that body's mass from the model. Nothing warns. This
    test asserts the broken behaviour on purpose: if MuJoCo ever changes it,
    `compile_floating` needs revisiting and this failure is the notification.
    """
    ir = _rover()
    welded = mujoco.MjModel.from_xml_string(to_urdf(ir))

    assert total_mass(welded) < _authored_mass(ir) * 0.9
    assert welded.nv == 4, "a welded base has only the wheel dofs, no 6-dof base"


def test_compile_floating_keeps_the_whole_robot():
    ir = _rover()
    model = compile_floating(ir)

    assert total_mass(model) == pytest.approx(_authored_mass(ir), rel=1e-6)
    # 6 dofs of free base + one per wheel.
    assert model.nv == 6 + 4


def test_compile_floating_adds_a_ground_plane():
    model = compile_floating(_rover())
    kinds = {int(model.geom_type[i]) for i in range(model.ngeom)}
    assert int(mujoco.mjtGeom.mjGEOM_PLANE) in kinds


def test_the_rover_settles_upright_on_the_plane():
    result = settle(compile_floating(_rover()))
    assert not result.diverged
    assert math.degrees(result.tilt_rad) < 6.0
    assert result.max_speed < 0.5


def test_torque_at_the_wheels_actually_moves_the_base():
    ir = _rover()
    model = compile_floating(ir)
    wheels = {j.id: 0.24 for j in ir.joints if j.kind == "revolute"}

    driven = drive(model, wheels)
    assert driven.travel > 0.005, "commanded torque produced no motion at all"
    assert set(driven.driven_joints) == set(wheels)


def test_zero_torque_moves_nothing():
    """Guards the drive test itself: if the robot drifts with no command, the
    measurement is picking up settling, not propulsion."""
    ir = _rover()
    driven = drive(compile_floating(ir), {j.id: 0.0 for j in ir.joints if j.kind == "revolute"})
    assert driven.travel < 0.005


def test_tier2_criteria_are_registered_and_reported():
    report = evaluate(_rover(), max_tier=2)
    assert report.tiers_run == [0, 1, 2]
    assert 2 not in report.tiers_skipped

    names = {r.name for r in report.results}
    assert {"sim_loads", "settles", "drives"} <= names


def test_sim_loads_verifies_mass_survived_translation():
    results = {r.name: r for r in evaluate(_rover(), max_tier=2).results}
    assert results["sim_loads"].passed
    assert results["sim_loads"].magnitude < 0.01


def test_drives_does_not_apply_to_a_robot_with_no_ground_contact_wheels():
    """simple_rover's wheel sits above its chassis, so it has no driven
    ground-contact joint. The criterion must not fire — an arm bolted to a bench
    is not a broken rover, and a criterion nobody can pass is as useless as one
    nobody can fail."""
    names = {r.name for r in evaluate(simple_rover(), max_tier=2).results}
    assert "drives" not in names
    # The rest of tier 2 still ran; only the inapplicable check is absent.
    assert {"sim_loads", "settles"} <= names


def test_a_wheeled_robot_with_no_motors_fails_drives():
    """The other half of the distinction above: wheels present, none actuated,
    is a defect rather than a category the robot falls outside of."""
    ir = _rover()
    stripped = ir.model_copy(deep=True)
    for joint in stripped.joints:
        joint.actuator = None

    results = {r.name: r for r in evaluate(stripped, max_tier=2).results}
    assert "drives" in results
    assert not results["drives"].passed
    assert "actuator" in results["drives"].detail


def test_a_wheel_with_positional_limits_welds_after_half_a_turn():
    """The bug tier 2 was built to catch, kept as a regression.

    The rover's drive joints were authored with limits of +/-pi and a provenance
    note reading "continuous rotation". Those are different claims: MuJoCo
    enforces the range, so the wheels rolled pi radians and stopped. The robot
    drove 34 mm of the 40 mm required while every tier-0 and tier-1 criterion
    passed — no static check can see it, because nothing static rotates.
    """
    ir = _rover()
    assert all(
        not j.limits.bounded for j in ir.joints if j.kind == "revolute" and j.limits
    ), "drive wheels must stay unbounded"

    free = drive(compile_floating(ir), {j.id: 0.24 for j in ir.joints if j.kind == "revolute"})

    bounded = ir.model_copy(deep=True)
    for joint in bounded.joints:
        if joint.kind == "revolute" and joint.limits is not None:
            joint.limits.lower = joint.limits.velocity.model_copy(
                update={"value": -math.pi, "unit": "rad"}
            )
            joint.limits.upper = joint.limits.velocity.model_copy(
                update={"value": math.pi, "unit": "rad"}
            )
    limited = drive(compile_floating(bounded), {j.id: 0.24 for j in bounded.joints if j.kind == "revolute"})

    assert limited.travel < free.travel / 10, (
        f"a bounded wheel should barely move: got {limited.travel:.3f}m "
        f"against {free.travel:.3f}m unbounded"
    )
    assert free.travel > 0.04


def test_an_uncompilable_model_reports_failure_rather_than_raising():
    """A model MuJoCo rejects is a result the agent needs to see, not a crash
    that takes the loop down."""
    import engine.sim.mujoco_harness as harness

    def _explode(_ir):
        raise RuntimeError("inertia of body 3 is not positive definite")

    saved = harness.compile_floating
    harness.compile_floating = _explode
    try:
        results = {r.name: r for r in evaluate(_rover(), max_tier=2).results}
        assert not results["sim_loads"].passed
        assert "positive definite" in results["sim_loads"].detail
        # The two checks that could not run are reported failing, never omitted.
        assert not results["settles"].passed
        assert not results["drives"].passed
    finally:
        harness.compile_floating = saved
