#!/usr/bin/env python3
"""Generate the fixture SO-101-class robot bundle deterministically (Shadow
Robot Spatial Demonstration Pipeline spec sections 9-11).

    uv run python tools/make_robot_bundle.py

Writes fixtures/spatial-training/robots/so101/{manifest,robot_ir,actuator}.json
and a physical copy of fixtures/robot/test_arm.urdf as robot.urdf.

The copy (not a symlink or shared reference) is deliberate: the old TEACH
pipeline's `ar_datapipe.robot_model.DEFAULT_URDF` keeps pointing at the
original file, untouched, so this new fixture tree can never accidentally
perturb it. `robot_ir.json`'s joint table is hand-authored to exactly mirror
test_arm.urdf (verified by this script's own test, see
tests/test_spatial_providers.py) rather than parsed from the URDF at
generation time — simplest safe choice for a fixture that doesn't change.
"""

from __future__ import annotations

import json
from pathlib import Path

ARVR_ROOT = Path(__file__).resolve().parent.parent
SOURCE_URDF = ARVR_ROOT / "fixtures" / "robot" / "test_arm.urdf"
BUNDLE_DIR = ARVR_ROOT / "fixtures" / "spatial-training" / "robots" / "so101"
PLACEHOLDER_GLB = ARVR_ROOT / "fixtures" / "ar-xr" / "robot.glb"


def write_json(path: Path, obj: object) -> None:
    path.write_text(json.dumps(obj, indent=2) + "\n")
    print(f"wrote {path.relative_to(ARVR_ROOT)}")


def make_robot_urdf_copy() -> None:
    BUNDLE_DIR.mkdir(parents=True, exist_ok=True)
    dest = BUNDLE_DIR / "robot.urdf"
    # The XML declaration (line 1) must be the very first thing in the file
    # -- a comment before it is invalid XML and urdfdom rejects it outright.
    # Insert this note as an XML comment right after that line instead.
    note = (
        "<!-- Physical copy of fixtures/robot/test_arm.urdf, generated by\n"
        "     tools/make_robot_bundle.py. Deliberately a copy, not a shared\n"
        "     reference -- the old TEACH pipeline's DEFAULT_URDF keeps\n"
        "     pointing at the original file, untouched. See STATE.md. -->\n"
    )
    source_lines = SOURCE_URDF.read_text().splitlines(keepends=True)
    xml_decl, rest = source_lines[0], source_lines[1:]
    dest.write_text(xml_decl + note + "".join(rest))
    print(f"wrote {dest.relative_to(ARVR_ROOT)} (copy of {SOURCE_URDF.relative_to(ARVR_ROOT)})")


def make_manifest() -> None:
    write_json(
        BUNDLE_DIR / "manifest.json",
        {
            "schema_version": "1.0",
            "robot_id": "fixture_so101",
            "source": "fixture",
            "robot_ir": "robot_ir.json",
            "urdf": "robot.urdf",
            # No dedicated SO-101 GLB exists yet -- reuse the existing
            # placeholder robot mesh. Visual fidelity for this fixture comes
            # from the procedural ShadowRobot renderer (xr-web), not this
            # file. See STATE.md's judgment-call log for this pivot.
            "visual_glb": "../../../ar-xr/robot.glb",
            "usd": None,
            "base_link": "base_link",
            "end_effectors": ["end_effector"],
        },
    )


# Mirrors fixtures/robot/test_arm.urdf exactly -- verified line-by-line
# against the URDF when this table was authored. Do not hand-edit without
# re-checking against the URDF; tests/test_spatial_providers.py cross-checks
# joint names (not axes/origins) against a live Pinocchio parse.
ROBOT_IR_JOINTS = [
    {
        "name": "shoulder_pan", "type": "revolute",
        "parent_link": "base_link", "child_link": "shoulder_link",
        "origin_position_m": [0.0, 0.0, 0.1], "axis": [0.0, 0.0, 1.0],
        "lower_limit": -3.14159, "upper_limit": 3.14159, "velocity_limit": 12.0,
    },
    {
        "name": "shoulder_lift", "type": "revolute",
        "parent_link": "shoulder_link", "child_link": "upper_arm_link",
        "origin_position_m": [0.0, 0.0, 0.05], "axis": [0.0, 1.0, 0.0],
        "lower_limit": -1.9199, "upper_limit": 1.9199, "velocity_limit": 6.0,
    },
    {
        "name": "elbow", "type": "revolute",
        "parent_link": "upper_arm_link", "child_link": "forearm_link",
        "origin_position_m": [0.4, 0.0, 0.0], "axis": [0.0, 1.0, 0.0],
        "lower_limit": -2.7925, "upper_limit": 2.7925, "velocity_limit": 6.0,
    },
    {
        "name": "wrist1", "type": "revolute",
        "parent_link": "forearm_link", "child_link": "wrist1_link",
        "origin_position_m": [0.4, 0.0, 0.0], "axis": [0.0, 0.0, 1.0],
        "lower_limit": -3.14159, "upper_limit": 3.14159, "velocity_limit": 18.0,
    },
    {
        "name": "wrist2", "type": "revolute",
        "parent_link": "wrist1_link", "child_link": "wrist2_link",
        "origin_position_m": [0.1, 0.0, 0.0], "axis": [0.0, 1.0, 0.0],
        "lower_limit": -1.9199, "upper_limit": 1.9199, "velocity_limit": 8.0,
    },
    {
        "name": "wrist3", "type": "revolute",
        "parent_link": "wrist2_link", "child_link": "wrist3_link",
        "origin_position_m": [0.0, 0.0, 0.0], "axis": [1.0, 0.0, 0.0],
        "lower_limit": -3.14159, "upper_limit": 3.14159, "velocity_limit": 15.0,
    },
    {
        "name": "wrist3_to_ee", "type": "fixed",
        "parent_link": "wrist3_link", "child_link": "end_effector",
        "origin_position_m": [0.08, 0.0, 0.0], "axis": None,
        "lower_limit": None, "upper_limit": None, "velocity_limit": None,
    },
]

ROBOT_IR_LINKS = [
    "base_link", "shoulder_link", "upper_arm_link", "forearm_link",
    "wrist1_link", "wrist2_link", "wrist3_link", "end_effector",
]


def make_robot_ir() -> None:
    write_json(
        BUNDLE_DIR / "robot_ir.json",
        {
            "schema_version": "1.0",
            "robot_id": "fixture_so101",
            "base_link": "base_link",
            "end_effector_frame": "end_effector",
            "links": ROBOT_IR_LINKS,
            "joints": ROBOT_IR_JOINTS,
        },
    )


def make_actuator() -> None:
    write_json(
        BUNDLE_DIR / "actuator.json",
        {
            "schema_version": "1.0",
            # test_arm.urdf has no gripper/finger articulation.
            "joints": [j["name"] for j in ROBOT_IR_JOINTS if j["type"] != "fixed"],
            "gripper": None,
        },
    )


def main() -> None:
    make_robot_urdf_copy()
    make_manifest()
    make_robot_ir()
    make_actuator()
    if not PLACEHOLDER_GLB.exists():
        print(
            f"warning: placeholder GLB {PLACEHOLDER_GLB} not found (run tools/make_assets.py)"
        )


if __name__ == "__main__":
    main()
