/**
 * STRUCT Can Pickup — the data-collection app.
 *
 * A human picks a can up off a table with their own hand, in front of a
 * laptop webcam. Every frame of that hand -- all the joints the tracker
 * reports -- plus the can's pose and what happened to it is recorded as a
 * `HumanEpisode` and exported as a LeRobot dataset for reinforcement
 * learning.
 *
 * There is no robot in the loop and deliberately so. The robot arm this data
 * is for is still being generated by the CAD half of the project, so there is
 * nothing to retarget onto yet -- and a `HumanEpisode` is robot-independent
 * by design, which is what lets the same recordings compile onto that arm the
 * moment it exists. The arm rendered here is the fixture SO-101, present for
 * scale and context, swapped for the generated one through `RobotProvider`
 * later with no change to anything downstream.
 *
 * The scene contains a table, a can, and the arm. Nothing else, because every
 * extra object is something a demonstrator can knock over and something a
 * policy has to learn to ignore.
 */

import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { GraspController } from "./grasp";
import { PinchLatch, pinchPoint, type HandPair } from "./hands";
import { ShadowHands } from "./shadowHand";
import { ShadowRobot } from "./shadowRobot";
import { WebcamHandProvider } from "./webcamHand";
import { CanPickupScene, buildCanSceneLighting } from "./canPickupScene";
import { CanPickupTask } from "./canPickupTask";
import {
  ARM_REST_POSE,
  CAN_ID,
  CAN_PICKUP_TASK_ID,
  CAN_RADIUS_M,
  CAN_START,
  LIFT_CLEARANCE_M,
  ROBOT_BASE,
  TABLE_Z_M,
} from "./canPickupLayout";
import { HumanEpisodeRecorder } from "./humanEpisodeRecorder";
import { exportHumanEpisodeForTraining, type HumanExportResult } from "./humanEpisodeUpload";
import { webxrToStruct } from "./adapter";
import type { Vec3 } from "./contracts";

const API_BASE = import.meta.env["VITE_API_BASE"] ?? "";

/**
 * How close the hand has to be to take the can.
 *
 * The can's own radius plus a hand's worth of slack. Webcam depth is
 * estimated rather than measured, so demanding centimetre precision here
 * would produce takes full of failed grabs -- which is worse than a
 * forgiving radius, because a failed grab is a recording of the wrong thing.
 */
const CAN_GRASP_RADIUS_M = CAN_RADIUS_M + 0.06;

const app = document.getElementById("app")!;
const readoutEl = document.getElementById("readout")!;
const controlsEl = document.getElementById("controls")!;
const statusEl = document.getElementById("status")!;
const videoPanelEl = document.getElementById("video-panel")!;

// ---------------------------------------------------------------- renderer --
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
app.appendChild(renderer.domElement);

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x14171c);
buildCanSceneLighting(scene);

const canScene = new CanPickupScene();
scene.add(canScene.root);

// The temporary arm. Real SO-101 geometry rather than a stand-in box, so the
// scale of the scene is honest about what this data is for.
const arm = new ShadowRobot();
arm.placeBase(ROBOT_BASE);
arm.setJoints(ARM_REST_POSE);
scene.add(arm.root);

const shadowHands = new ShadowHands();
scene.add(shadowHands.root);

const camera = new THREE.PerspectiveCamera(50, innerWidth / innerHeight, 0.01, 50);
camera.position.set(0.62, 0.42, 0.55);
const orbit = new OrbitControls(camera, renderer.domElement);
orbit.target.set(0, TABLE_Z_M + 0.06, -0.24);
orbit.enableDamping = true;
orbit.update();

addEventListener("resize", () => {
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
});

// ------------------------------------------------------------------- state --
const task = new CanPickupTask();

/**
 * A grasp and a pinch latch per hand.
 *
 * Either hand may pick the can up -- a demonstrator should use whichever is
 * natural, and forcing one would bias every recording toward it. Tracking a
 * single hand is also how the webcam provider's `preferredHandIndex` picks
 * MediaPipe's camera-side "Right", which with a mirrored preview is the
 * user's LEFT hand; sidestepping that entirely is better than depending on
 * which side a label happens to mean.
 */
const hands = {
  left: { grasp: new GraspController(CAN_GRASP_RADIUS_M), pinch: new PinchLatch() },
  right: { grasp: new GraspController(CAN_GRASP_RADIUS_M), pinch: new PinchLatch() },
};

let provider: WebcamHandProvider | undefined;
let tracking = false;
let handTracked = false;
let reachable = false;
let lastFrameMs: number | undefined;

let recorder: HumanEpisodeRecorder | undefined;
let recording = false;
let framesRecorded = 0;
let eventsRecorded = 0;
let exportResult: HumanExportResult | undefined;
let exportError: string | undefined;
let exportPending = false;
/** Episodes exported this session, so a demonstrator can see they are
 * building a dataset rather than repeating one recording. */
let episodesSaved = 0;

// -------------------------------------------------------------------- HUD --
interface ControlSpec {
  id: string;
  label: string;
  action: () => void;
  className?: string;
  disabled?: boolean;
}

function controlSpecs(): ControlSpec[] {
  if (!tracking) {
    return [{ id: "camera", label: "START CAMERA", action: () => void startCamera() }];
  }
  if (recording) {
    return [
      { id: "stop", label: "STOP & SAVE", action: () => void stopRecording(), className: "rec" },
      { id: "discard", label: "DISCARD", action: discardRecording },
    ];
  }
  return [
    { id: "record", label: "RECORD", action: startRecording },
    { id: "reset", label: "RESET CAN", action: resetTask },
  ];
}

function renderControls(): void {
  controlsEl.replaceChildren();
  for (const spec of controlSpecs()) {
    const button = document.createElement("button");
    button.textContent = spec.label;
    if (spec.className) button.className = spec.className;
    button.onclick = spec.action;
    button.disabled = spec.disabled ?? false;
    controlsEl.appendChild(button);
  }
  renderReadout();
}

function renderReadout(): void {
  statusEl.textContent = recording ? "● RECORDING" : tracking ? "READY" : "CAMERA OFF";
  statusEl.dataset["state"] = recording ? "recording" : tracking ? "ready" : "off";

  const lines = [
    `task      ${CAN_PICKUP_TASK_ID}`,
    `object    ${CAN_ID}`,
    `hand      ${handTracked ? "TRACKED" : "—"}`,
    `grasp     ${task.isHeld ? "HOLDING" : reachable ? "IN REACH" : "—"}`,
    `lift      ${task.wasLifted ? `✓ (>${(LIFT_CLEARANCE_M * 100).toFixed(0)}cm)` : "—"}`,
  ];

  if (recording) lines.push("", `frames    ${framesRecorded}`);
  else if (exportPending) lines.push("", "saving…");
  else if (exportError) lines.push("", "SAVE FAILED", exportError.slice(0, 120));
  else if (exportResult) {
    lines.push(
      "",
      "EPISODE SAVED",
      `frames    ${exportResult.frames}`,
      `dataset   ${exportResult.dataset_id ?? "—"}`,
    );
  }
  if (episodesSaved > 0) lines.push("", `episodes this session: ${episodesSaved}`);

  // Webcam depth is inferred, not measured. Saying so on screen keeps it from
  // being forgotten by the time this data reaches whoever trains on it.
  if (tracking) lines.push("", "DEPTH  ESTIMATED (single camera)");

  readoutEl.textContent = lines.join("\n");
}

// ------------------------------------------------------------------ camera --
async function startCamera(): Promise<void> {
  try {
    provider = await WebcamHandProvider.create();
    videoPanelEl.appendChild(provider.videoElement);
    videoPanelEl.classList.add("active");
    provider.startPair(onHandPair);
    tracking = true;
  } catch (error) {
    statusEl.textContent = "CAMERA FAILED";
    readoutEl.textContent = `Could not start the webcam:\n${String(error)}`;
  }
  renderControls();
}

// -------------------------------------------------------------- recording --
function nowNs(): number {
  return Math.round(performance.now() * 1e6);
}

function resetTask(): void {
  task.reset();
  for (const side of ["left", "right"] as const) {
    hands[side].grasp.clear();
    hands[side].pinch.reset();
  }
  eventsRecorded = 0;
  renderControls();
}

function startRecording(): void {
  // Each take starts from the same scene state, so every episode in the
  // dataset begins with the can in the same place. A policy trained on takes
  // that each started somewhere different has to learn the variation as
  // signal.
  resetTask();

  recorder = new HumanEpisodeRecorder({
    taskId: CAN_PICKUP_TASK_ID,
    assetId: CAN_ID,
    handProvider: "webcam",
  });
  recorder.start(nowNs());
  recorder.markEvent("task_start", nowNs());

  recording = true;
  framesRecorded = 0;
  exportResult = undefined;
  exportError = undefined;
  renderControls();
}

function discardRecording(): void {
  recorder?.cancel();
  recorder = undefined;
  recording = false;
  renderControls();
}

async function stopRecording(): Promise<void> {
  if (!recorder) return;
  recording = false;
  recorder.markEvent("task_finish", nowNs());
  exportPending = true;
  renderControls();

  const metadata = recorder.finish();
  try {
    exportResult = await exportHumanEpisodeForTraining(
      API_BASE,
      metadata,
      recorder.handFrames(),
      recorder.objectStates(),
      recorder.events(),
    );
    exportError = undefined;
    episodesSaved += 1;
  } catch (error) {
    // The take is gone from the recorder either way, so a failure has to be
    // stated loudly rather than looking like a save.
    exportError = String(error);
    exportResult = undefined;
  }
  exportPending = false;
  recorder = undefined;
  renderControls();
}

// -------------------------------------------------------------- hand loop --
/**
 * One frame of tracked hands.
 *
 * Either hand may take the can, so both are offered a grasp. The can is a
 * single object, so once one hand has it the other is offered nothing --
 * without that, both hands would own it and fight over its position every
 * frame.
 *
 * The webcam provider authors struct_world positions through its control
 * volume, but emits them in WebXR axes, which is what `webxrToStruct`
 * converts here.
 */
function onHandPair(pair: HandPair): void {
  const timestampNs = nowNs();
  shadowHands.update(pair);

  const anyTracked = pair.left !== null || pair.right !== null;
  if (!anyTracked && handTracked && recording) task.markTrackingLost();
  handTracked = anyTracked;

  reachable = false;

  for (const side of ["right", "left"] as const) {
    const hand = pair[side];
    const track = hands[side];

    const pinchWebxr = hand ? pinchPoint(hand) : null;
    const pinchStruct = pinchWebxr ? (webxrToStruct.position(pinchWebxr) as Vec3) : null;
    track.pinch.update(hand ? { gripper: hand.gripper } : null);

    const canPosition = task.canPosition();
    // Offer the can only if it is free, or already held by *this* hand.
    const offered = !task.isHeld || track.grasp.held === CAN_ID;
    const result = track.grasp.update({
      pinchActive: track.pinch.isEngaged,
      pinchCenter: pinchStruct,
      handOrientation: [0, 0, 0, 1],
      balls: offered ? [{ id: CAN_ID, position: canPosition }] : [],
    });

    if (result.grasped) task.setHeld(true);
    if (result.released) task.setHeld(false);
    if (result.heldId && result.ballPosition) task.setCanPosition(result.ballPosition);

    if (pinchStruct && offered) {
      const reach = Math.hypot(
        canPosition[0] - pinchStruct[0],
        canPosition[1] - pinchStruct[1],
        canPosition[2] - pinchStruct[2],
      );
      if (reach <= CAN_GRASP_RADIUS_M) reachable = true;
    }
  }

  const now = performance.now();
  const dt = lastFrameMs === undefined ? 1 / 30 : (now - lastFrameMs) / 1000;
  lastFrameMs = now;
  task.step(Math.min(dt, 0.05));

  if (recording && recorder) {
    // Both hands under one timestamp: a dataset row is one instant, not one
    // hand. The recorder's monotonic check rejects going backwards, not
    // repeating an instant, so this is allowed by design.
    for (const hand of [pair.left, pair.right]) {
      if (hand) recorder.captureHand(hand, timestampNs);
    }
    framesRecorded = recorder.frameCount;

    recorder.captureObject({
      id: CAN_ID,
      position_m: task.canPosition(),
      timestamp_ns: timestampNs,
    });
    for (const event of task.events.slice(eventsRecorded)) {
      recorder.markEvent(mapEvent(event.type), timestampNs, { objectId: CAN_ID });
    }
    eventsRecorded = task.events.length;
  }

  renderReadout();
}

/** The task's own vocabulary onto the recorded event vocabulary. `lifted` and
 * `placed` have no counterpart in the frozen contract, so they map onto the
 * nearest honest thing rather than being invented into it. */
function mapEvent(type: string): "grasp_start" | "grasp_end" | "contact" | "task_finish" | "tracking_lost" {
  switch (type) {
    case "grasp_start": return "grasp_start";
    case "grasp_end": return "grasp_end";
    case "tracking_lost": return "tracking_lost";
    case "task_success": return "task_finish";
    default: return "contact";
  }
}

// ------------------------------------------------------------ render loop --
renderer.setAnimationLoop(() => {
  orbit.update();
  canScene.update(task, reachable);
  renderer.render(scene, camera);
});

canScene.update(task, false);
renderControls();

// Keep the starting can pose visible in the readout even before the camera
// starts, so the scene is legible on load.
void CAN_START;
