/**
 * STRUCT Mug Pickup — the data-collection app.
 *
 * A human picks a mug up off a table with their own hand, in front of a
 * laptop webcam. Every frame of that hand -- all the joints the tracker
 * reports -- plus the mug's pose and what happened to it is recorded as a
 * `HumanEpisode` and exported as a LeRobot dataset for reinforcement
 * learning.
 *
 * There is no robot in the loop and deliberately so. The robot arm this data
 * is for is still being generated by the CAD half of the project, so there is
 * nothing to retarget onto yet -- and a `HumanEpisode` is robot-independent
 * by design, which is what lets the same recordings compile onto that arm the
 * moment it exists. The arm rendered here is the fixture SO-101, present for
 * scale and context, swapped for the generated one through `RobotProvider`
 * later with no change to anything downstream.
 *
 * The scene contains a table, a mug, and the arm. Nothing else, because every
 * extra object is something a demonstrator can knock over and something a
 * policy has to learn to ignore.
 */

import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { GraspController } from "./grasp";
import { GripLatch, graspClosure, pinchPoint, type HandPair } from "./hands";
import { ShadowHands } from "./shadowHand";
import { WebcamHandProvider } from "./webcamHand";
import { MugPickupScene, buildMugSceneLighting } from "./mugPickupScene";
import { MugPickupTask } from "./mugPickupTask";
import {
  MUG_CONTROL_VOLUME,
  MUG_ID,
  MUG_PICKUP_TASK_ID,
  MUG_BODY_RADIUS_M,
  MUG_START,
  LIFT_CLEARANCE_M,
  TABLE_Z_M,
} from "./mugPickupLayout";
import { HumanEpisodeRecorder } from "./humanEpisodeRecorder";
import { exportHumanEpisodeForTraining, type HumanExportResult } from "./humanEpisodeUpload";
import { webxrToStruct } from "./adapter";
import type { Vec3 } from "./contracts";

const API_BASE = import.meta.env["VITE_API_BASE"] ?? "";

/**
 * How close the hand has to be to take the mug.
 *
 * The mug body's radius plus a hand's worth of slack. Webcam depth is
 * estimated rather than measured, so demanding centimetre precision here
 * would produce takes full of failed grabs -- which is worse than a
 * forgiving radius, because a failed grab is a recording of the wrong thing.
 *
 * Measured to the mug's origin, which is the centre of its base, so the
 * radius also has to cover reaching for the middle of the body rather than
 * down at the table.
 */
const MUG_GRASP_RADIUS_M = MUG_BODY_RADIUS_M + 0.09;

const app = document.getElementById("app")!;
const readoutEl = document.getElementById("readout")!;
const controlsEl = document.getElementById("controls")!;
const statusEl = document.getElementById("status")!;
const videoPanelEl = document.getElementById("video-panel")!;
const cameraSelectEl = document.getElementById("camera-select") as HTMLSelectElement;

// ---------------------------------------------------------------- renderer --
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
app.appendChild(renderer.domElement);

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x14171c);
buildMugSceneLighting(scene);

const mugScene = new MugPickupScene();
scene.add(mugScene.root);

const shadowHands = new ShadowHands();
scene.add(shadowHands.root);

const camera = new THREE.PerspectiveCamera(50, innerWidth / innerHeight, 0.01, 50);
camera.position.set(0.62, 0.42, 0.55);
const orbit = new OrbitControls(camera, renderer.domElement);
orbit.target.set(0, TABLE_Z_M + 0.06, -0.24);
orbit.enableDamping = true;
orbit.update();

addEventListener("resize", () => {
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
});

// ------------------------------------------------------------------- state --
const task = new MugPickupTask();

/**
 * A grasp and a pinch latch per hand.
 *
 * Either hand may pick the mug up -- a demonstrator should use whichever is
 * natural, and forcing one would bias every recording toward it. Tracking a
 * single hand is also how the webcam provider's `preferredHandIndex` picks
 * MediaPipe's camera-side "Right", which with a mirrored preview is the
 * user's LEFT hand; sidestepping that entirely is better than depending on
 * which side a label happens to mean.
 */
const hands = {
  left: { grasp: new GraspController(MUG_GRASP_RADIUS_M), grip: new GripLatch() },
  right: { grasp: new GraspController(MUG_GRASP_RADIUS_M), grip: new GripLatch() },
};

let provider: WebcamHandProvider | undefined;
let tracking = false;
let handTracked = false;
let reachable = false;
let lastFrameMs: number | undefined;
/** Last struct_world hand position and its distance to the mug, shown in the
 * readout so a hand that is tracked but out of reach is visibly that. */
let handPosition: Vec3 | undefined;
let handToCanM = Infinity;
/** How curled the nearest hand is, shown so a demonstrator can watch the
 * grab arm rather than guess why nothing happened. */
let handClosure = 0;

let recorder: HumanEpisodeRecorder | undefined;
let recording = false;
let framesRecorded = 0;
let eventsRecorded = 0;
let exportResult: HumanExportResult | undefined;
let exportError: string | undefined;
let exportPending = false;
/** Episodes exported this session, so a demonstrator can see they are
 * building a dataset rather than repeating one recording. */
let episodesSaved = 0;

// -------------------------------------------------------------------- HUD --
interface ControlSpec {
  id: string;
  label: string;
  action: () => void;
  className?: string;
  disabled?: boolean;
}

function controlSpecs(): ControlSpec[] {
  if (!tracking) {
    return [{ id: "camera", label: "START CAMERA", action: () => void startCamera() }];
  }
  if (recording) {
    return [
      { id: "stop", label: "STOP & SAVE", action: () => void stopRecording(), className: "rec" },
      { id: "discard", label: "DISCARD", action: discardRecording },
    ];
  }
  return [
    { id: "record", label: "RECORD", action: startRecording },
    { id: "reset", label: "RESET CAN", action: resetTask },
  ];
}

function renderControls(): void {
  controlsEl.replaceChildren();
  for (const spec of controlSpecs()) {
    const button = document.createElement("button");
    button.textContent = spec.label;
    if (spec.className) button.className = spec.className;
    button.onclick = spec.action;
    button.disabled = spec.disabled ?? false;
    controlsEl.appendChild(button);
  }
  renderReadout();
}

function renderReadout(): void {
  statusEl.textContent = recording ? "● RECORDING" : tracking ? "READY" : "CAMERA OFF";
  statusEl.dataset["state"] = recording ? "recording" : tracking ? "ready" : "off";

  const lines = [
    `task      ${MUG_PICKUP_TASK_ID}`,
    `object    ${MUG_ID}`,
    `hand      ${handTracked ? "TRACKED" : "—"}`,
    `grasp     ${task.isHeld ? "HOLDING" : reachable ? "IN REACH" : "—"}`,
    `lift      ${task.wasLifted ? `✓ (>${(LIFT_CLEARANCE_M * 100).toFixed(0)}cm)` : "—"}`,
  ];

  if (recording) lines.push("", `frames    ${framesRecorded}`);
  else if (exportPending) lines.push("", "saving…");
  else if (exportError) lines.push("", "SAVE FAILED", exportError.slice(0, 120));
  else if (exportResult) {
    lines.push(
      "",
      "EPISODE SAVED",
      `frames    ${exportResult.frames}`,
      `dataset   ${exportResult.dataset_id ?? "—"}`,
    );
  }
  if (episodesSaved > 0) lines.push("", `episodes this session: ${episodesSaved}`);

  // Everything needed to tell "the camera is off" from "the camera is on but
  // sees no hand" from "it sees a hand but it is nowhere near the mug".
  // Without these three numbers all of those look identical on screen, which
  // is exactly how a control volume that could not reach the mug presented
  // as "nothing happens".
  if (tracking) {
    const status = provider?.getStatus();
    lines.push(
      "",
      `tracker   ${status ? `${status.resultFps.toFixed(0)} fps` : "starting…"}`,
      `detected  ${status?.handedness ?? "no hand in frame"}`,
      `grip      ${(handClosure * 100).toFixed(0)}%  (grabs at 55%)`,
    );
    if (handPosition) {
      lines.push(
        `hand xyz  ${handPosition.map((v) => v.toFixed(2)).join(", ")}`,
        `mug  xyz  ${task.mugPosition().map((v) => v.toFixed(2)).join(", ")}`,
        `distance  ${(handToCanM * 100).toFixed(0)}cm  (grab under ${(MUG_GRASP_RADIUS_M * 100).toFixed(0)}cm)`,
      );
    }
    lines.push("", "DEPTH  ESTIMATED (single camera)");
  }

  readoutEl.textContent = lines.join("\n");
}

// ------------------------------------------------------------------ camera --
/**
 * List the cameras available to the browser.
 *
 * A phone streamed in as a virtual webcam (Iriun, Camo, EpocCam) shows up
 * here like any other device, and is usually the better choice: phone optics
 * beat a laptop webcam badly, and -- more importantly -- a phone can be
 * placed to the SIDE. Depth toward a laptop's fixed forward-facing camera is
 * the one direction it cannot see; from the side, that same motion is
 * lateral, which monocular tracking measures directly. None of these
 * virtual cameras carry a depth channel, so this improves the input rather
 * than changing what is being inferred.
 *
 * Labels are only populated after camera permission has been granted, so
 * this is called again once a stream is open.
 */
async function refreshCameraList(): Promise<void> {
  if (!navigator.mediaDevices?.enumerateDevices) return;
  let devices: MediaDeviceInfo[];
  try {
    devices = await navigator.mediaDevices.enumerateDevices();
  } catch (error) {
    console.warn("could not enumerate cameras:", error);
    return;
  }

  const cameras = devices.filter((d) => d.kind === "videoinput");
  const previous = cameraSelectEl.value;
  cameraSelectEl.replaceChildren();

  const auto = document.createElement("option");
  auto.value = "";
  auto.textContent = "DEFAULT";
  cameraSelectEl.appendChild(auto);

  for (const [i, camera] of cameras.entries()) {
    const option = document.createElement("option");
    option.value = camera.deviceId;
    // Before permission is granted the label is empty by design (it would
    // otherwise be a fingerprinting vector), so fall back to a number rather
    // than rendering a row of blanks.
    option.textContent = camera.label || `CAMERA ${i + 1}`;
    cameraSelectEl.appendChild(option);
  }
  if (previous) cameraSelectEl.value = previous;
}

void refreshCameraList();

/** Switching camera mid-session restarts tracking on the new device. */
cameraSelectEl.addEventListener("change", () => {
  if (!tracking) return;
  provider?.stop();
  provider = undefined;
  tracking = false;
  void startCamera();
});

async function startCamera(): Promise<void> {
  try {
    const deviceId = cameraSelectEl.value;
    provider = await WebcamHandProvider.create({
      controlVolume: MUG_CONTROL_VOLUME,
      ...(deviceId ? { cameraDeviceId: deviceId } : {}),
    });
    // Labels only become readable once permission exists, so re-list now
    // that a stream is open -- otherwise the picker stays a list of numbers.
    void refreshCameraList();
    videoPanelEl.appendChild(provider.videoElement);
    videoPanelEl.classList.add("active");
    provider.startPair(onHandPair);
    tracking = true;
  } catch (error) {
    statusEl.textContent = "CAMERA FAILED";
    readoutEl.textContent = `Could not start the webcam:\n${String(error)}`;
  }
  renderControls();
}

// -------------------------------------------------------------- recording --
function nowNs(): number {
  return Math.round(performance.now() * 1e6);
}

function resetTask(): void {
  task.reset();
  for (const side of ["left", "right"] as const) {
    hands[side].grasp.clear();
    hands[side].grip.reset();
  }
  eventsRecorded = 0;
  renderControls();
}

function startRecording(): void {
  // Each take starts from the same scene state, so every episode in the
  // dataset begins with the mug in the same place. A policy trained on takes
  // that each started somewhere different has to learn the variation as
  // signal.
  resetTask();

  recorder = new HumanEpisodeRecorder({
    taskId: MUG_PICKUP_TASK_ID,
    assetId: MUG_ID,
    handProvider: "webcam",
  });
  recorder.start(nowNs());
  recorder.markEvent("task_start", nowNs());

  recording = true;
  framesRecorded = 0;
  exportResult = undefined;
  exportError = undefined;
  renderControls();
}

function discardRecording(): void {
  recorder?.cancel();
  recorder = undefined;
  recording = false;
  renderControls();
}

async function stopRecording(): Promise<void> {
  if (!recorder) return;
  recording = false;
  recorder.markEvent("task_finish", nowNs());
  exportPending = true;
  renderControls();

  const metadata = recorder.finish();
  try {
    exportResult = await exportHumanEpisodeForTraining(
      API_BASE,
      metadata,
      recorder.handFrames(),
      recorder.objectStates(),
      recorder.events(),
    );
    exportError = undefined;
    episodesSaved += 1;
  } catch (error) {
    // The take is gone from the recorder either way, so a failure has to be
    // stated loudly rather than looking like a save.
    exportError = String(error);
    exportResult = undefined;
  }
  exportPending = false;
  recorder = undefined;
  renderControls();
}

// -------------------------------------------------------------- hand loop --
/**
 * One frame of tracked hands.
 *
 * Either hand may take the mug, so both are offered a grasp. The mug is a
 * single object, so once one hand has it the other is offered nothing --
 * without that, both hands would own it and fight over its position every
 * frame.
 *
 * The webcam provider authors struct_world positions through its control
 * volume, but emits them in WebXR axes, which is what `webxrToStruct`
 * converts here.
 */
function onHandPair(pair: HandPair): void {
  const timestampNs = nowNs();
  shadowHands.update(pair);

  const anyTracked = pair.left !== null || pair.right !== null;
  if (!anyTracked && handTracked && recording) task.markTrackingLost();
  handTracked = anyTracked;

  reachable = false;
  handToCanM = Infinity;
  handPosition = undefined;
  handClosure = 0;

  for (const side of ["right", "left"] as const) {
    const hand = pair[side];
    const track = hands[side];

    const pinchWebxr = hand ? pinchPoint(hand) : null;
    const pinchStruct = pinchWebxr ? (webxrToStruct.position(pinchWebxr) as Vec3) : null;
    // Grip, not pinch: a mug is taken with the whole hand, and thumb-index
    // aperture reads that as an open hand (see graspClosure).
    track.grip.update(hand);

    const mugPosition = task.mugPosition();
    // Offer the mug only if it is free, or already held by *this* hand.
    const offered = !task.isHeld || track.grasp.held === MUG_ID;
    const result = track.grasp.update({
      pinchActive: track.grip.isEngaged,
      pinchCenter: pinchStruct,
      handOrientation: [0, 0, 0, 1],
      balls: offered ? [{ id: MUG_ID, position: mugPosition }] : [],
    });

    if (result.grasped) task.setHeld(true);
    if (result.released) task.setHeld(false);
    if (result.heldId && result.ballPosition) task.setMugPosition(result.ballPosition);

    if (pinchStruct) {
      const reach = Math.hypot(
        mugPosition[0] - pinchStruct[0],
        mugPosition[1] - pinchStruct[1],
        mugPosition[2] - pinchStruct[2],
      );
      if (reach < handToCanM) {
        handToCanM = reach;
        handPosition = pinchStruct;
        handClosure = hand ? graspClosure(hand) : 0;
      }
      if (offered && reach <= MUG_GRASP_RADIUS_M) reachable = true;
    }
  }

  // Feed the ground marker whichever hand is nearest the mug -- that is the
  // one the demonstrator is aiming with.
  mugScene.updateHand(handPosition ?? null);

  const now = performance.now();
  const dt = lastFrameMs === undefined ? 1 / 30 : (now - lastFrameMs) / 1000;
  lastFrameMs = now;
  task.step(Math.min(dt, 0.05));

  if (recording && recorder) {
    // Both hands under one timestamp: a dataset row is one instant, not one
    // hand. The recorder's monotonic check rejects going backwards, not
    // repeating an instant, so this is allowed by design.
    for (const hand of [pair.left, pair.right]) {
      if (hand) recorder.captureHand(hand, timestampNs);
    }
    framesRecorded = recorder.frameCount;

    recorder.captureObject({
      id: MUG_ID,
      position_m: task.mugPosition(),
      timestamp_ns: timestampNs,
    });
    for (const event of task.events.slice(eventsRecorded)) {
      recorder.markEvent(mapEvent(event.type), timestampNs, { objectId: MUG_ID });
    }
    eventsRecorded = task.events.length;
  }
}

/** The task's own vocabulary onto the recorded event vocabulary. `lifted` and
 * `placed` have no counterpart in the frozen contract, so they map onto the
 * nearest honest thing rather than being invented into it. */
function mapEvent(type: string): "grasp_start" | "grasp_end" | "contact" | "task_finish" | "tracking_lost" {
  switch (type) {
    case "grasp_start": return "grasp_start";
    case "grasp_end": return "grasp_end";
    case "tracking_lost": return "tracking_lost";
    case "task_success": return "task_finish";
    default: return "contact";
  }
}

// ------------------------------------------------------------ render loop --
renderer.setAnimationLoop(() => {
  orbit.update();
  mugScene.update(task, reachable);

  // The readout is driven from here, not from the hand callback.
  //
  // That callback only fires when a hand is actually detected, so hanging the
  // HUD off it means that when nothing is detected -- the exact case a person
  // needs to debug -- the panel freezes at its last value and the app looks
  // dead. Every diagnostic it shows becomes unreachable in the only situation
  // it was added for. Redrawing every frame costs nothing and makes "camera
  // on, no hand seen" a state you can actually read.
  renderReadout();

  renderer.render(scene, camera);
});

mugScene.update(task, false);
renderControls();

// Keep the starting can pose visible in the readout even before the camera
// starts, so the scene is legible on load.
void MUG_START;
