/**
 * The mug-pickup scene: a table and a mug. Nothing else.
 *
 * This is the task the project records. A human picks a mug up off a table
 * with their own hand, moves it, and puts it back down, and that
 * demonstration becomes reinforcement-learning data for a robot arm learning
 * to grasp and place objects.
 *
 * There is no robot in this scene. The data is *for* a robot, but the
 * recording is of a human hand and an object, and rendering an arm that is
 * neither being controlled nor being retargeted onto adds nothing a
 * demonstrator can use.
 *
 * Frame: right-handed, Z-up, meters. The tabletop is the z = 0 plane, which
 * is also struct_world's origin plane -- so everything on the table sits at
 * small positive Z and the table body hangs below.
 */

import type { Vec3 } from "./contracts";

/** The tabletop is the origin plane. See the module docstring. */
export const TABLE_Z_M = 0;

/** How far the table body drops below its surface. Visual only. */
export const TABLE_DROP_M = 0.72;

/** Table footprint. Comfortably larger than the reachable area so the mug
 * always has surface under it, without filling the whole view. */
export const TABLE_X_M: [number, number] = [-0.12, 0.46];
export const TABLE_Y_M: [number, number] = [-0.30, 0.30];
export const TABLE_THICKNESS_M = 0.02;

/**
 * The mug, as generated by `tools/make_mug_asset.py`.
 *
 * A standard 12oz / 355ml stoneware mug: 89mm tall, 82mm across the body,
 * with a handle protruding on its local +X to an overall 113.5mm. Both the
 * body and the handle are declared graspable in the asset's
 * `interaction.json`, because a person may reasonably take either.
 *
 * These numbers mirror the generator. If it is re-run with different
 * dimensions, these must change with it -- the asset is the source of truth
 * for the mesh, and this is the source of truth for where the mesh goes.
 */
export const MUG_ID = "mug_01";
export const MUG_ASSET_URL = "/spatial-training/assets/mug/asset.glb";
export const MUG_HEIGHT_M = 0.089;
export const MUG_BODY_RADIUS_M = 0.041;

/**
 * Where the mug's *base* sits, not its centre.
 *
 * The generated asset's local origin is the centre of its base, so the
 * position below is the point the mug rests on. Treating it as a centre
 * would leave the mug hovering half its height above the table -- a mistake
 * worth naming, because the previous stand-in cylinder used centre-origin
 * and the two conventions are indistinguishable until you look.
 */
export const MUG_START: Vec3 = [0.26, 0.0, TABLE_Z_M];

/**
 * How far the mug's base must clear the table to count as picked up.
 *
 * 8cm is unambiguous: well past hand-tracking noise, and clearly a
 * deliberate lift rather than the mug being nudged or tipped. The predicate
 * is deterministic and the number is stated rather than tuned by eye,
 * because "did this demonstration succeed" decides what enters the training
 * set.
 */
export const LIFT_CLEARANCE_M = 0.08;
export const LIFT_THRESHOLD_Z_M = TABLE_Z_M + LIFT_CLEARANCE_M;

export const MUG_PICKUP_TASK_ID = "pick_up_mug";

/**
 * Where the webcam maps your hand to, in struct_world.
 *
 * The provider turns image position into a point inside this box: image
 * left/right sweeps struct X, image up/down sweeps struct Z, and apparent
 * hand size sweeps struct Y (depth). The box has to *contain the mug*, or
 * the hand can never reach it -- an earlier version inherited a box whose
 * floor sat above the object, and the hand tracked perfectly while being
 * unable to touch anything.
 *
 * The floor is slightly below the tabletop so the mug's base is comfortably
 * inside, and the ceiling is high enough to lift well past the success
 * threshold.
 */
export const MUG_CONTROL_VOLUME = {
  xMin: 0.10, xMax: 0.42,
  yMin: -0.18, yMax: 0.18,
  zMin: -0.01, zMax: 0.34,
};
